language: node_js
node_js:
- 8
- 10
before_install:
- npm install -g npm
script:
- npm install
- npm run pretest
deploy:
  provider: heroku
  api_key:
    secure: pkk3fTx9H865NU0luBEHYCti3Qe1j52nXW1xGTUGDi/XtrXmibJlHTTgNLZ7Zmw55reGOVuvc3naYzC4M0S6h762Le8Wcdh97glTPo6Az/bLtMfB8W9ERvy024f9dZBHhop9vSNfsTGFWQNHD7pGeM3ZjfaQMn/diqKOVHqFn6U9Qb5zxKdwJaePb75TxVjJDCB1V2/V2hGcuzb69yTOhUtRZbaN60KXwTO7xjyRrQ//00tHJbKMgKC1jGktNDHjJpZE406CV3sPLxogVrmGkWL6rDvyKfpxSHrI5khIlVqNjTx9F8QwsqbiuVIXzUKo95RPQmy9tD0mDRrQiH0UaDu4UIyGkNmFwKVzakFxrosHjJc/m31nI3nuT2WSknjg9zZnDvNuAmndMpoE7tfqdqgkpcdodG831vwljGc9sgS6h1F66MDY/RFus9RYuE8SuzRDcqwPqfytxSGAOpuFSy7WGmS2mHPza5de2oFrHHnyDcM6aVI2Ki2P35A4o8iNch4eIQtPI8hyy51EI0TRx0SVcUcANigOTJk9L/phQ2BT8q6Ik4BqLL9ie8RUwXo6QURCz/KgnJcxRXeXVjh8Oe1dw/JlbZtip9kZKUcBh0859OdoNbugfhuZI2CJ5t5HrxoKjwSdvHVOQvj2y5vVrOQcTok/DfLtFYTg9zH2eaY=
  app: krazzy-cric-app
  on:
    repo: abdullasulaiman/krazzy-cric-app
